version: "3.8"

services:
  malbec:
    build: .
    environment:
      MONGO_URL: "mongodb://admin:admin@mongodb:27017/malbecDB"
      PORT: "3000"
      SECRETPASS: "SebasMalbec"
      JWT_KEY: "SebasToken"
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src
      - /usr/src/node_modules

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: malbecDB
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
